# new .drone.yml syntax

clone:
  path: github.com/cjb/golang-test-client

compose:
  golang-test-server:
    image: cjbprime/golang-test-server

build:
  image: golang:1.4.2
  commands:
    - export GOPATH=/drone
    - export PATH=$PATH:$GOPATH/bin
    - go build -o client/client ./...
    - ./client/client
